version: '3.8'

services:
  web:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - php
    restart: unless-stopped

  php:
    build: ./docker/php
    volumes:
      - ./public:/var/www/html
    expose:
      - "9000"
    restart: unless-stopped

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: realestate
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
