FROM php:8.1-fpm-alpine

# Устанавливаем расширения PDO_MySQL и MySQLi для подключения к БД
RUN docker-php-ext-install pdo pdo_mysql mysqli

# При необходимости можно добавить другие расширения или настройки
